const PictureData = [
  {
    id: "1",
    idProj: "2",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz1.jpeg",
    Asli: 0,
  },
  {
    id: "2",
    idProj: "2",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz2.jpg",
    Asli: 0,
  },
  {
    id: "3",
    idProj: "2",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz3.jpg",
    Asli: 1,
  },
  {
    id: "4",
    idProj: "2",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz4.jpeg",
    Asli: 0,
  },
  {
    id: "5",
    idProj: "2",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz5.jpeg",
    Asli: 0,
  },
  {
    id: "6",
    idProj: "2",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz6.JPG",
    Asli: 0,
  },
  {
    id: "7",
    idProj: "2",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz7.jpg",
    Asli: 0,
  },
  {
    id: "8",
    idProj: "2",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz8.JPG",
    Asli: 0,
  },
  {
    id: "9",
    idProj: "2",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz9.jpg",
    Asli: 1,
  },
  {
    id: "10",
    idProj: "2",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz10.JPG",
    Asli: 0,
  },
  {
    id: "11",
    idProj: "2",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz11.JPG",
    Asli: 0,
  },
  {
    id: "12",
    idProj: "2",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz12.JPG",
    Asli: 0,
  },
  {
    id: "13",
    idProj: "2",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz13.JPG",
    Asli: 1,
  },
  {
    id: "14",
    idProj: "2",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz14.JPG",
    Asli: 0,
  },
  {
    id: "15",
    idProj: "2",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz15.JPG",
    Asli: 0,
  },
  {
    id: "16",
    idProj: "2",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz16.JPG",
    Asli: 0,
  },
  {
    id: "17",
    idProj: "2",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz17.JPG",
    Asli: 1,
  },
  {
    id: "18",
    idProj: "2",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz18.jpg",
    Asli: 0,
  },
  {
    id: "19",
    idProj: "2",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz19.jpg",
    Asli: 0,
  },
  {
    id: "20",
    idProj: "2",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz20.jpg",
    Asli: 0,
  },

  {
    id: "41",
    idProj: "1",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran1.jpg",
    Asli: 0,
  },
  {
    id: "42",
    idProj: "1",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran2.jpg",
    Asli: 1,
  },
  {
    id: "43",
    idProj: "1",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran3.jpg",
    Asli: 0,
  },
  {
    id: "44",
    idProj: "1",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran4.jpg",
    Asli: 0,
  },
  {
    id: "45",
    idProj: "1",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran5.jpg",
    Asli: 0,
  },
  {
    id: "46",
    idProj: "1",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran6.jpg",
    Asli: 0,
  },
  {
    id: "47",
    idProj: "1",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran7.jpg",
    Asli: 0,
  },
  {
    id: "48",
    idProj: "1",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran8.jpg",
    Asli: 0,
  },
  {
    id: "49",
    idProj: "1",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran9.jpg",
    Asli: 0,
  },
  {
    id: "50",
    idProj: "1",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran10.jpg",
    Asli: 0,
  },
  {
    id: "51",
    idProj: "1",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran11.jpg",
    Asli: 0,
  },
  {
    id: "52",
    idProj: "1",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran12.jpg",
    Asli: 0,
  },
  {
    id: "53",
    idProj: "1",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran13.jpg",
    Asli: 1,
  },
  {
    id: "54",
    idProj: "1",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran14.jpg",
    Asli: 0,
  },
  {
    id: "55",
    idProj: "1",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran15.jpg",
    Asli: 0,
  },
  {
    id: "56",
    idProj: "1",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran16.jpg",
    Asli: 0,
  },
  {
    id: "57",
    idProj: "1",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran17.jpg",
    Asli: 0,
  },

  {
    id: "98",
    idProj: "4",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan1.jpeg",
    Asli: 0,
  },
  {
    id: "99",
    idProj: "4",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan2.jpeg",
    Asli: 0,
  },
  {
    id: "100",
    idProj: "4",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan3.jpeg",
    Asli: 0,
  },
  {
    id: "101",
    idProj: "4",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan4.jpg",
    Asli: 0,
  },
  {
    id: "102",
    idProj: "4",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan5.jpg",
    Asli: 0,
  },
  {
    id: "103",
    idProj: "4",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan6.jpg",
    Asli: 0,
  },
  {
    id: "104",
    idProj: "4",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan7.jpg",
    Asli: 0,
  },
  {
    id: "105",
    idProj: "4",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan8.jpg",
    Asli: 0,
  },
  {
    id: "106",
    idProj: "4",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan9.jpg",
    Asli: 0,
  },
  {
    id: "107",
    idProj: "4",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan10.jpg",
    Asli: 0,
  },
  {
    id: "108",
    idProj: "4",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan11.jpg",
    Asli: 1,
  },
  {
    id: "109",
    idProj: "4",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan12.jpg",
    Asli: 0,
  },
  {
    id: "110",
    idProj: "4",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan13.jpg",
    Asli: 0,
  },
  {
    id: "111",
    idProj: "4",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan14.jpg",
    Asli: 0,
  },
  {
    id: "112",
    idProj: "4",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan15.jpg",
    Asli: 0,
  },
  {
    id: "113",
    idProj: "4",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan16.jpg",
    Asli: 0,
  },
  {
    id: "142",
    idProj: "10",
    name: " تصفیه خانه فاضلاب شهر رودان ",
    pic: "/images/projects/roodan1.JPG",
    Asli: 0,
  },
  {
    id: "143",
    idProj: "10",
    name: " تصفیه خانه فاضلاب شهر رودان ",
    pic: "/images/projects/roodan2.JPG",
    Asli: 1,
  },
  {
    id: "144",
    idProj: "10",
    name: " تصفیه خانه فاضلاب شهر رودان ",
    pic: "/images/projects/roodan3.JPG",
    Asli: 0,
  },
  {
    id: "145",
    idProj: "10",
    name: " تصفیه خانه فاضلاب شهر رودان ",
    pic: "/images/projects/roodan4.JPG",
    Asli: 0,
  },
  {
    id: "146",
    idProj: "10",
    name: " تصفیه خانه فاضلاب شهر رودان ",
    pic: "/images/projects/roodan5.JPG",
    Asli: 0,
  },
  {
    id: "147",
    idProj: "10",
    name: " تصفیه خانه فاضلاب شهر رودان ",
    pic: "/images/projects/roodan6.JPG",
    Asli: 1,
  },
  {
    id: "148",
    idProj: "10",
    name: " تصفیه خانه فاضلاب شهر رودان ",
    pic: "/images/projects/roodan7.JPG",
    Asli: 0,
  },
  {
    id: "149",
    idProj: "10",
    name: " تصفیه خانه فاضلاب شهر رودان ",
    pic: "/images/projects/roodan8.JPG",
    Asli: 0,
  },
  {
    id: "150",
    idProj: "10",
    name: " تصفیه خانه فاضلاب شهر رودان ",
    pic: "/images/projects/roodan9.JPG",
    Asli: 0,
  },
  {
    id: "151",
    idProj: "10",
    name: " تصفیه خانه فاضلاب شهر رودان ",
    pic: "/images/projects/roodan10.JPG",
    Asli: 0,
  },
  {
    id: "152",
    idProj: "10",
    name: " تصفیه خانه فاضلاب شهر رودان ",
    pic: "/images/projects/roodan11.JPG",
    Asli: 0,
  },
  {
    id: "153",
    idProj: "8",
    name: " تصفیه خانه فاضلاب شهر محمود آباد",
    pic: "/images/projects/mahmoodabad1.JPG",
    Asli: 0,
  },
  {
    id: "154",
    idProj: "8",
    name: " تصفیه خانه فاضلاب شهر محمود آباد",
    pic: "/images/projects/mahmoodabad2.JPG",
    Asli: 1,
  },
  {
    id: "155",
    idProj: "3",
    name: " تصفیه خانه آب شهر ساری",
    pic: "/images/projects/sariWT1.jpg",
    Asli: 0,
  },
  {
    id: "156",
    idProj: "3",
    name: " تصفیه خانه آب شهر ساری",
    pic: "/images/projects/sariWT2.jpg",
    Asli: 1,
  },
  {
    id: "157",
    idProj: "3",
    name: " تصفیه خانه آب شهر ساری",
    pic: "/images/projects/sariWT3.jpg",
    Asli: 0,
  },
  {
    id: "158",
    idProj: "3",
    name: " تصفیه خانه آب شهر ساری",
    pic: "/images/projects/sariWT4.jpg",
    Asli: 0,
  },
  {
    id: "159",
    idProj: "3",
    name: " تصفیه خانه آب شهر ساری",
    pic: "/images/projects/sariWT5.jpeg",
    Asli: 1,
  },
  {
    id: "160",
    idProj: "3",
    name: " تصفیه خانه آب شهر ساری",
    pic: "/images/projects/sariWT6.jpg",
    Asli: 0,
  },
  {
    id: "161",
    idProj: "3",
    name: " تصفیه خانه آب شهر ساری",
    pic: "/images/projects/sariWT7.jpeg",
    Asli: 0,
  },
  {
    id: "162",
    idProj: "3",
    name: " تصفیه خانه آب شهر ساری",
    pic: "/images/projects/sariWT8.jpg",
    Asli: 0,
  },
  {
    id: "163",
    idProj: "3",
    name: " تصفیه خانه آب شهر ساری",
    pic: "/images/projects/sariWT9.jpg",
    Asli: 0,
  },
  {
    id: "164",
    idProj: "3",
    name: " تصفیه خانه آب شهر ساری",
    pic: "/images/projects/sariWT10.jpg",
    Asli: 0,
  },
  {
    id: "165",
    idProj: "3",
    name: " تصفیه خانه آب شهر ساری",
    pic: "/images/projects/sariWT11.jpg",
    Asli: 0,
  },
  {
    id: "166",
    idProj: "3",
    name: " تصفیه خانه آب شهر ساری",
    pic: "/images/projects/sariWT12.jpg",
    Asli: 0,
  },
  {
    id: "167",
    idProj: "3",
    name: " تصفیه خانه آب شهر ساری",
    pic: "/images/projects/sariWT13.jpg",
    Asli: 1,
  },
  {
    id: "168",
    idProj: "3",
    name: " تصفیه خانه آب شهر ساری",
    pic: "/images/projects/sariWT14.jpg",
    Asli: 0,
  },
  {
    id: "169",
    idProj: "3",
    name: " تصفیه خانه آب شهر ساری",
    pic: "/images/projects/sariWT15.jpg",
    Asli: 0,
  },
  {
    id: "170",
    idProj: "3",
    name: " تصفیه خانه آب شهر ساری",
    pic: "/images/projects/sariWT16.jpg",
    Asli: 0,
  },
  {
    id: "171",
    idProj: "3",
    name: " تصفیه خانه آب شهر ساری",
    pic: "/images/projects/sariWT17.jpg",
    Asli: 0,
  },
  {
    id: "172",
    idProj: "3",
    name: " تصفیه خانه آب شهر ساری",
    pic: "/images/projects/sariWT18.jpg",
    Asli: 0,
  },

  {
    id: "175",
    idProj: "5",
    name: " تصفیه خانه آب شهر بم",
    pic: "/images/projects/bam1.jpg",
    Asli: 1,
  },
  {
    id: "176",
    idProj: "5",
    name: " تصفیه خانه آب شهر بم",
    pic: "/images/projects/bam2.jpg",
    Asli: 0,
  },
  {
    id: "177",
    idProj: "5",
    name: " تصفیه خانه آب شهر بم",
    pic: "/images/projects/bam3.jpg",
    Asli: 0,
  },

  {
    id: "179",
    idProj: "7",
    name: " تصفیه خانه آب شهر خلخال",
    pic: "/images/projects/khalkhal1.jpeg",
    Asli: 0,
  },
  {
    id: "180",
    idProj: "7",
    name: " تصفیه خانه آب شهر خلخال",
    pic: "/images/projects/khalkhal2.jpeg",
    Asli: 1,
  },
  {
    id: "181",
    idProj: "7",
    name: " تصفیه خانه آب شهر خلخال",
    pic: "/images/projects/khalkhal3.jpeg",
    Asli: 0,
  },
  {
    id: "182",
    idProj: "7",
    name: " تصفیه خانه آب شهر خلخال",
    pic: "/images/projects/khalkhal4.jpeg",
    Asli: 0,
  },

  {
    id: "190",
    idProj: "29",
    name: " تصفیه خانه فاضلاب صنایع لاستیک تایر کرد",
    pic: "/images/projects/tayerKord1.jpg",
    Asli: 1,
  },
  {
    id: "191",
    idProj: "29",
    name: " تصفیه خانه فاضلاب صنایع لاستیک تایر کرد",
    pic: "/images/projects/tayerKord2.jpg",
    Asli: 0,
  },

  {
    id: "319",
    idProj: "29",
    name: " تصفیه خانه فاضلاب صنایع لاستیک تایر کرد",
    pic: "/images/projects/tayerKord4.jpg",
    Asli: 3,
  },
  {
    id: "192",
    idProj: "29",
    name: " تصفیه خانه فاضلاب صنایع لاستیک تایر کرد",
    pic: "/images/projects/tayerKord3.jpg",
    Asli: 3,
  },
  {
    id: "193",
    idProj: "30",
    name: " تصفیه خانه فاضلاب شهرک صنعتی شهید سلیمی ",
    pic: "/images/projects/shahidS1.JPG",
    Asli: 1,
  },
  {
    id: "194",
    idProj: "30",
    name: " تصفیه خانه فاضلاب شهرک صنعتی شهید سلیمی ",
    pic: "/images/projects/shahidS2.JPG",
    Asli: 0,
  },
  {
    id: "195",
    idProj: "31",
    name: " تصفیه خانه فاضلاب شهرک صنعتی شمس آباد ",
    pic: "/images/projects/shamsabad1.jpg",
    Asli: 0,
  },
  {
    id: "196",
    idProj: "31",
    name: " تصفیه خانه فاضلاب شهرک صنعتی شمس آباد ",
    pic: "/images/projects/shamsabad2.jpg",
    Asli: 1,
  },
  {
    id: "197",
    idProj: "6",
    name: " تصفیه خانه فاضلاب بهارستان ",
    pic: "/images/projects/baharestan1.JPG",
    Asli: 0,
  },
  {
    id: "198",
    idProj: "6",
    name: " تصفیه خانه فاضلاب بهارستان ",
    pic: "/images/projects/baharestan2.JPG",
    Asli: 0,
  },
  {
    id: "199",
    idProj: "6",
    name: " تصفیه خانه فاضلاب بهارستان ",
    pic: "/images/projects/baharestan3.JPG",
    Asli: 0,
  },
  {
    id: "200",
    idProj: "6",
    name: " تصفیه خانه فاضلاب بهارستان ",
    pic: "/images/projects/baharestan4.JPG",
    Asli: 0,
  },
  {
    id: "201",
    idProj: "6",
    name: " تصفیه خانه فاضلاب بهارستان ",
    pic: "/images/projects/baharestan5.JPG",
    Asli: 1,
  },
  {
    id: "202",
    idProj: "6",
    name: " تصفیه خانه فاضلاب بهارستان ",
    pic: "/images/projects/baharestan6.JPG",
    Asli: 0,
  },
  {
    id: "203",
    idProj: "6",
    name: " تصفیه خانه فاضلاب بهارستان ",
    pic: "/images/projects/baharestan7.JPG",
    Asli: 0,
  },
  {
    id: "204",
    idProj: "6",
    name: " تصفیه خانه فاضلاب بهارستان ",
    pic: "/images/projects/baharestan8.JPG",
    Asli: 0,
  },

  {
    id: "207",
    idProj: "32",
    name: " تصفیه خانه فاضلاب شهرک صنعتی بهارستان ",
    pic: "/images/projects/baharestanS1.jpg",
    Asli: 0,
  },
  {
    id: "208",
    idProj: "32",
    name: " تصفیه خانه فاضلاب شهرک صنعتی بهارستان ",
    pic: "/images/projects/baharestanS2.jpg",
    Asli: 1,
  },
  {
    id: "209",
    idProj: "21",
    name: " تصفیه خانه اضطراری آب عباس آباد همدان ",
    pic: "/images/projects/hamedan1.jpg",
    Asli: 0,
  },
  {
    id: "210",
    idProj: "21",
    name: " تصفیه خانه اضطراری آب عباس آباد همدان ",
    pic: "/images/projects/hamedan2.jpg",
    Asli: 1,
  },
  {
    id: "211",
    idProj: "21",
    name: " تصفیه خانه اضطراری آب عباس آباد همدان ",
    pic: "/images/projects/hamedan3.jpg",
    Asli: 0,
  },
  {
    id: "212",
    idProj: "20",
    name: " تصفیه خانه فاضلاب شهر اردبیل ",
    pic: "/images/projects/ardebil1.jpg",
    Asli: 0,
  },
  {
    id: "213",
    idProj: "20",
    name: " تصفیه خانه فاضلاب شهر اردبیل ",
    pic: "/images/projects/ardebil2.jpg",
    Asli: 1,
  },
  {
    id: "214",
    idProj: "20",
    name: " تصفیه خانه فاضلاب شهر اردبیل ",
    pic: "/images/projects/ardebil3.jpg",
    Asli: 0,
  },

  {
    id: "217",
    idProj: "11",
    name: " تصفیه خانه آب شهر تکاب ",
    pic: "/images/projects/takab1.JPG",
    Asli: 1,
  },
  {
    id: "218",
    idProj: "11",
    name: " تصفیه خانه آب شهر تکاب ",
    pic: "/images/projects/takab2.JPG",
    Asli: 1,
  },
  {
    id: "219",
    idProj: "11",
    name: " تصفیه خانه آب شهر تکاب ",
    pic: "/images/projects/takab3.JPG",
    Asli: 0,
  },
  {
    id: "220",
    idProj: "11",
    name: " تصفیه خانه آب شهر تکاب ",
    pic: "/images/projects/takab4.JPG",
    Asli: 0,
  },
  {
    id: "221",
    idProj: "11",
    name: " تصفیه خانه آب شهر تکاب ",
    pic: "/images/projects/takab5.JPG",
    Asli: 0,
  },
  {
    id: "222",
    idProj: "11",
    name: " تصفیه خانه آب شهر تکاب ",
    pic: "/images/projects/takab6.JPG",
    Asli: 1,
  },
  {
    id: "223",
    idProj: "11",
    name: " تصفیه خانه آب شهر تکاب ",
    pic: "/images/projects/takab7.jpg",
    Asli: 0,
  },
  {
    id: "224",
    idProj: "12",
    name: " تصفیه خانه فاضلاب شهر مهاباد ",
    pic: "/images/projects/mahabad1.jpg",
    Asli: 0,
  },
  {
    id: "225",
    idProj: "12",
    name: " تصفیه خانه فاضلاب شهر مهاباد ",
    pic: "/images/projects/mahabad2.jpg",
    Asli: 0,
  },
  {
    id: "226",
    idProj: "12",
    name: " تصفیه خانه فاضلاب شهر مهاباد ",
    pic: "/images/projects/mahabad3.JPG",
    Asli: 1,
  },
  {
    id: "227",
    idProj: "12",
    name: " تصفیه خانه فاضلاب شهر مهاباد ",
    pic: "/images/projects/mahabad4.JPG",
    Asli: 0,
  },
  {
    id: "228",
    idProj: "12",
    name: " تصفیه خانه فاضلاب شهر مهاباد ",
    pic: "/images/projects/mahabad5.JPG",
    Asli: 1,
  },
  {
    id: "229",
    idProj: "12",
    name: " تصفیه خانه فاضلاب شهر مهاباد ",
    pic: "/images/projects/mahabad6.jpg",
    Asli: 0,
  },
  {
    id: "320",
    idProj: "12",
    name: " تصفیه خانه فاضلاب شهر مهاباد ",
    pic: "/images/projects/mahabad7.jpg",
    Asli: 0,
  },
  {
    id: "321",
    idProj: "12",
    name: " تصفیه خانه فاضلاب شهر مهاباد ",
    pic: "/images/projects/mahabad8.jpg",
    Asli: 0,
  },
  {
    id: "322",
    idProj: "12",
    name: " تصفیه خانه فاضلاب شهر مهاباد ",
    pic: "/images/projects/mahabad9.jpg",
    Asli: 0,
  },
  {
    id: "323",
    idProj: "12",
    name: " تصفیه خانه فاضلاب شهر مهاباد ",
    pic: "/images/projects/mahabad10.jpg",
    Asli: 0,
  },
  {
    id: "324",
    idProj: "12",
    name: " تصفیه خانه فاضلاب شهر مهاباد ",
    pic: "/images/projects/mahabad11.jpg",
    Asli: 0,
  },
  {
    id: "325",
    idProj: "12",
    name: " تصفیه خانه فاضلاب شهر مهاباد ",
    pic: "/images/projects/mahabad12.jpg",
    Asli: 0,
  },
  {
    id: "230",
    idProj: "22",
    name: " تصفیه خانه فاضلاب شهر بندر گز ",
    pic: "/images/projects/bandarGaz1.jpg",
    Asli: 1,
  },
  {
    id: "231",
    idProj: "22",
    name: " تصفیه خانه فاضلاب شهر بندر گز ",
    pic: "/images/projects/bandarGaz2.JPG",
    Asli: 0,
  },
  {
    id: "232",
    idProj: "22",
    name: " تصفیه خانه فاضلاب شهر بندر گز ",
    pic: "/images/projects/bandarGaz3.JPG",
    Asli: 0,
  },

  {
    id: "234",
    idProj: "13",
    name: " تصفیه خانه فاضلاب دزفول ",
    pic: "/images/projects/dezfool1.jpg",
    Asli: 1,
  },
  {
    id: "235",
    idProj: "13",
    name: " تصفیه خانه فاضلاب دزفول ",
    pic: "/images/projects/dezfool2.jpg",
    Asli: 0,
  },
  {
    id: "326",
    idProj: "13",
    name: " تصفیه خانه فاضلاب دزفول ",
    pic: "/images/projects/dezfool3.jpg",
    Asli: 0,
  },
  {
    id: "327",
    idProj: "13",
    name: " تصفیه خانه فاضلاب دزفول ",
    pic: "/images/projects/dezfool4.jpg",
    Asli: 0,
  },
  {
    id: "328",
    idProj: "13",
    name: " تصفیه خانه فاضلاب دزفول ",
    pic: "/images/projects/dezfool5.jpg",
    Asli: 0,
  },
  {
    id: "236",
    idProj: "23",
    name: " تصفیه خانه فاضلاب سمنان ",
    pic: "/images/projects/saman1.jpg",
    Asli: 0,
  },
  {
    id: "237",
    idProj: "23",
    name: " تصفیه خانه فاضلاب سمنان ",
    pic: "/images/projects/saman2.jpg",
    Asli: 1,
  },
  {
    id: "238",
    idProj: "23",
    name: " تصفیه خانه فاضلاب سمنان ",
    pic: "/images/projects/saman3.jpg",
    Asli: 0,
  },
  {
    id: "239",
    idProj: "25",
    name: " تلمبه خانه فاضلاب ساری ",
    pic: "/images/projects/sariP1.JPG",
    Asli: 1,
  },
  {
    id: "240",
    idProj: "25",
    name: " تلمبه خانه فاضلاب ساری ",
    pic: "/images/projects/sariP2.JPG",
    Asli: 0,
  },
  {
    id: "241",
    idProj: "25",
    name: " تلمبه خانه فاضلاب ساری ",
    pic: "/images/projects/sariP3.JPG",
    Asli: 0,
  },
  {
    id: "242",
    idProj: "25",
    name: " تلمبه خانه فاضلاب ساری ",
    pic: "/images/projects/sariP4.JPG",
    Asli: 0,
  },
  {
    id: "243",
    idProj: "25",
    name: " تلمبه خانه فاضلاب ساری ",
    pic: "/images/projects/sariP5.JPG",
    Asli: 0,
  },

  {
    id: "245",
    idProj: "15",
    name: " تصفیه خانه فاضلاب شهر کردکوی",
    pic: "/images/projects/kordkooy1.JPG",
    Asli: 0,
  },
  {
    id: "246",
    idProj: "15",
    name: " تصفیه خانه فاضلاب شهر کردکوی",
    pic: "/images/projects/kordkooy2.JPG",
    Asli: 0,
  },
  {
    id: "247",
    idProj: "15",
    name: " تصفیه خانه فاضلاب شهر کردکوی",
    pic: "/images/projects/kordkooy3.JPG",
    Asli: 0,
  },
  {
    id: "329",
    idProj: "15",
    name: " تصفیه خانه فاضلاب شهر کردکوی",
    pic: "/images/projects/kordkooy4.JPG",
    Asli: 0,
  },
  {
    id: "330",
    idProj: "15",
    name: " تصفیه خانه فاضلاب شهر کردکوی",
    pic: "/images/projects/kordkooy5.JPG",
    Asli: 0,
  },
  {
    id: "331",
    idProj: "15",
    name: " تصفیه خانه فاضلاب شهر کردکوی",
    pic: "/images/projects/kordkooy6.JPG",
    Asli: 0,
  },
  {
    id: "332",
    idProj: "15",
    name: " تصفیه خانه فاضلاب شهر کردکوی",
    pic: "/images/projects/kordkooy7.JPG",
    Asli: 0,
  },
  {
    id: "248",
    idProj: "9",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin1.JPG",
    Asli: 1,
  },
  {
    id: "249",
    idProj: "9",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin2.JPG",
    Asli: 0,
  },
  {
    id: "250",
    idProj: "9",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin3.JPG",
    Asli: 0,
  },
  {
    id: "251",
    idProj: "9",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin4.jpg",
    Asli: 0,
  },
  {
    id: "252",
    idProj: "9",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin5.jpg",
    Asli: 0,
  },
  {
    id: "253",
    idProj: "9",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin6.jpg",
    Asli: 0,
  },
  {
    id: "254",
    idProj: "9",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin7.jpg",
    Asli: 0,
  },
  {
    id: "255",
    idProj: "9",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin8.JPG",
    Asli: 0,
  },
  {
    id: "256",
    idProj: "9",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin9.JPG",
    Asli: 0,
  },
  {
    id: "257",
    idProj: "9",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin10.JPG",
    Asli: 0,
  },
  {
    id: "258",
    idProj: "9",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin11.JPG",
    Asli: 0,
  },
  {
    id: "259",
    idProj: "9",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin12.JPG",
    Asli: 0,
  },
  {
    id: "260",
    idProj: "9",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin13.JPG",
    Asli: 0,
  },
  {
    id: "261",
    idProj: "9",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin14.JPG",
    Asli: 0,
  },
  {
    id: "262",
    idProj: "9",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin15.JPG",
    Asli: 0,
  },
  {
    id: "263",
    idProj: "9",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin16.JPG",
    Asli: 0,
  },
  {
    id: "264",
    idProj: "9",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin17.JPG",
    Asli: 0,
  },
  {
    id: "265",
    idProj: "9",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin18.JPG",
    Asli: 0,
  },
  {
    id: "266",
    idProj: "9",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin19.JPG",
    Asli: 0,
  },
  {
    id: "267",
    idProj: "9",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin20.JPG",
    Asli: 1,
  },
  {
    id: "268",
    idProj: "9",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin21.JPG",
    Asli: 0,
  },
  {
    id: "269",
    idProj: "9",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin22.JPG",
    Asli: 1,
  },
  {
    id: "270",
    idProj: "9",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin23.JPG",
    Asli: 0,
  },
  {
    id: "271",
    idProj: "9",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin24.JPG",
    Asli: 0,
  },
  {
    id: "272",
    idProj: "9",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin25.JPG",
    Asli: 1,
  },
  {
    id: "273",
    idProj: "14",
    name: " تصفیه خانه فاضلاب تویسرکان",
    pic: "/images/projects/tooyserkan1.jpg",
    Asli: 0,
  },
  {
    id: "274",
    idProj: "14",
    name: " تصفیه خانه فاضلاب تویسرکان",
    pic: "/images/projects/tooyserkan2.jpg",
    Asli: 1,
  },

  {
    id: "282",
    idProj: "17",
    name: " تصفیه خانه فاضلاب سامان",
    pic: "/images/projects/saman1.jpg",
    Asli: 0,
  },
  {
    id: "283",
    idProj: "17",
    name: " تصفیه خانه فاضلاب سامان",
    pic: "/images/projects/saman2.jpg",
    Asli: 0,
  },
  {
    id: "284",
    idProj: "17",
    name: " تصفیه خانه فاضلاب سامان",
    pic: "/images/projects/saman3.jpg",
    Asli: 0,
  },
  {
    id: "285",
    idProj: "16",
    name: " تصفیه خانه فاضلاب شهر پاوه",
    pic: "/images/projects/paveh1.jpg",
    Asli: 1,
  },
  {
    id: "286",
    idProj: "16",
    name: " تصفیه خانه فاضلاب شهر پاوه",
    pic: "/images/projects/paveh2.jpg",
    Asli: 0,
  },
  {
    id: "287",
    idProj: "16",
    name: " تصفیه خانه فاضلاب شهر پاوه",
    pic: "/images/projects/paveh3.JPG",
    Asli: 0,
  },
  {
    id: "288",
    idProj: "16",
    name: " تصفیه خانه فاضلاب شهر پاوه",
    pic: "/images/projects/paveh4.JPG",
    Asli: 0,
  },
  {
    id: "289",
    idProj: "16",
    name: " تصفیه خانه فاضلاب شهر پاوه",
    pic: "/images/projects/paveh5.jpg",
    Asli: 0,
  },
  {
    id: "290",
    idProj: "18",
    name: " تصفیه خانه فاضلاب عجب شیر ",
    pic: "/images/projects/ajabshir1.jpg",
    Asli: 1,
  },
  {
    id: "291",
    idProj: "18",
    name: " تصفیه خانه فاضلاب عجب شیر ",
    pic: "/images/projects/ajabshir2.jpg",
    Asli: 0,
  },
  {
    id: "292",
    idProj: "18",
    name: " تصفیه خانه فاضلاب عجب شیر ",
    pic: "/images/projects/ajabshir3.jpg",
    Asli: 0,
  },
  {
    id: "333",
    idProj: "18",
    name: " تصفیه خانه فاضلاب عجب شیر ",
    pic: "/images/projects/ajabshir4.jpg",
    Asli: 0,
  },
  {
    id: "334",
    idProj: "18",
    name: " تصفیه خانه فاضلاب عجب شیر ",
    pic: "/images/projects/ajabshir5.jpg",
    Asli: 0,
  },
  {
    id: "335",
    idProj: "18",
    name: " تصفیه خانه فاضلاب عجب شیر ",
    pic: "/images/projects/ajabshir6.jpg",
    Asli: 0,
  },
  {
    id: "336",
    idProj: "18",
    name: " تصفیه خانه فاضلاب عجب شیر ",
    pic: "/images/projects/ajabshir7.jpg",
    Asli: 0,
  },
  {
    id: "337",
    idProj: "18",
    name: " تصفیه خانه فاضلاب عجب شیر ",
    pic: "/images/projects/ajabshir8.jpg",
    Asli: 0,
  },
  {
    id: "338",
    idProj: "18",
    name: " تصفیه خانه فاضلاب عجب شیر ",
    pic: "/images/projects/ajabshir9.jpg",
    Asli: 0,
  },
  {
    id: "293",
    idProj: "19",
    name: " تصفیه خانه فاضلاب ملایر ",
    pic: "/images/projects/malayer1.jpg",
    Asli: 0,
  },
  {
    id: "294",
    idProj: "19",
    name: " تصفیه خانه فاضلاب ملایر ",
    pic: "/images/projects/malayer2.JPG",
    Asli: 0,
  },
  {
    id: "295",
    idProj: "19",
    name: " تصفیه خانه فاضلاب ملایر ",
    pic: "/images/projects/malayer3.JPG",
    Asli: 1,
  },
  {
    id: "296",
    idProj: "19",
    name: " تصفیه خانه فاضلاب ملایر ",
    pic: "/images/projects/malayer4.JPG",
    Asli: 0,
  },
  {
    id: "297",
    idProj: "19",
    name: " تصفیه خانه فاضلاب ملایر ",
    pic: "/images/projects/malayer5.JPG",
    Asli: 0,
  },
  {
    id: "298",
    idProj: "19",
    name: " تصفیه خانه فاضلاب ملایر ",
    pic: "/images/projects/malayer6.JPG",
    Asli: 0,
  },

  {
    id: "307",
    idProj: "28",
    name: " آبرسانی به صنایع  مستقر در ایجرود از سد گلابر شهرستان ایجرود ",
    pic: "/images/projects/Ijrood1.png",
    Asli: 1,
  },
  {
    id: "308",
    idProj: "28",
    name: " آبرسانی به صنایع  مستقر در ایجرود از سد گلابر شهرستان ایجرود ",
    pic: "/images/projects/Ijrood2.png",
    Asli: 0,
  },
  {
    id: "309",
    idProj: "28",
    name: " آبرسانی به صنایع  مستقر در ایجرود از سد گلابر شهرستان ایجرود ",
    pic: "/images/projects/Ijrood3.png",
    Asli: 0,
  },
  {
    id: "310",
    idProj: "28",
    name: " آبرسانی به صنایع  مستقر در ایجرود از سد گلابر شهرستان ایجرود ",
    pic: "/images/projects/Ijrood4.png",
    Asli: 0,
  },
  {
    id: "311",
    idProj: "26",
    name: " تلمبه خانه برداشت آب از سد جگین ",
    pic: "/images/projects/jegin1.JPG",
    Asli: 0,
  },
  {
    id: "312",
    idProj: "26",
    name: " تلمبه خانه برداشت آب از سد جگین",
    pic: "/images/projects/jegin2.JPG",
    Asli: 1,
  },
  {
    id: "313",
    idProj: "24",
    name: " تصفیه خانه آب شهر میانه",
    pic: "/images/projects/Mianeh1.png",
    Asli: 1,
  },
  {
    id: "314",
    idProj: "24",
    name: " تصفیه خانه آب شهر میانه",
    pic: "/images/projects/Mianeh2.png",
    Asli: 0,
  },
  {
    id: "315",
    idProj: "24",
    name: " تصفیه خانه آب شهر میانه",
    pic: "/images/projects/Mianeh3.jpeg",
    Asli: 0,
  },
  {
    id: "339",
    idProj: "24",
    name: " تصفیه خانه آب شهر میانه",
    pic: "/images/projects/Mianeh4.jpg",
    Asli: 0,
  },
  {
    id: "316",
    idProj: "27",
    name: " آبگیر شناور طرح آبرسانی به شهر جهرم از سد سلمان فارسی ",
    pic: "/images/projects/jahrom1.jpg",
    Asli: 0,
  },
  {
    id: "317",
    idProj: "27",
    name: " آبگیر شناور طرح آبرسانی به شهر جهرم از سد سلمان فارسی ",
    pic: "/images/projects/jahrom2.jpg",
    Asli: 1,
  },
  {
    id: "318",
    idProj: "27",
    name: " آبگیر شناور طرح آبرسانی به شهر جهرم از سد سلمان فارسی ",
    pic: "/images/projects/jahrom3.jpg",
    Asli: 0,
  },
];
export { PictureData };
