const ProcessStepData = [
  { id: "1", idProj: "5", processStep: "واحد هوادهی آبشاری" },
  { id: "2", idProj: "5", processStep: "واحد آشغالگیر دهانه ریز" },
  { id: "3", idProj: "5", processStep: "واحد میکرواسترینر" },
  { id: "4", idProj: "5", processStep: "واحد انعقاد (اختلاط سریع )" },
  { id: "5", idProj: "5", processStep: "واحد آماده سازی و تزریق مواد شیمیایی" },
  { id: "6", idProj: "5", processStep: "واحد ته نشینی (پولساتور )" },
  {
    id: "7",
    idProj: "5",
    processStep: "واحد فیلتراسیون (فیلتر شنی سریع با سیستم بکواش هوا و آب )",
  },
  {
    id: "8",
    idProj: "5",
    processStep: "واحد کلرزنی (تولید هیپوکلریت سدیم به روش الکترولیز نمک طعام)",
  },
  { id: "9", idProj: "5", processStep: "واحد تغلیظ لجن (ثقلی )" },
  { id: "10", idProj: "5", processStep: "واحد آبگیری لجن (بلت فیلترپرس)" },
  { id: "11", idProj: "5", processStep: "واحد بازیافت آب بک واش " },
  {
    id: "12",
    idProj: "5",
    processStep: "تلمبه خانه لجن غلیظ شده و برگشت زهاب و اب سرویس ",
  },
  { id: "13", idProj: "5", processStep: "مخزن 10000 مترمکعبی آب پاک" },
  { id: "14", idProj: "24", processStep: "شیرخانه ورودی" },
  { id: "15", idProj: "24", processStep: "واحد هوادهی آبشاری" },
  { id: "16", idProj: "24", processStep: "واحد آشغالگیری" },
  { id: "17", idProj: "24", processStep: "واحد انعقاد (اختلاط سریع )" },
  {
    id: "18",
    idProj: "24",
    processStep: "واحد آماده سازی و تزریق مواد شیمیایی ",
  },
  { id: "19", idProj: "24", processStep: "واحد ته نشینی شیمیایی مقدماتی" },
  { id: "20", idProj: "24", processStep: "واحد ته نشینی (پولساتور )" },
  {
    id: "21",
    idProj: "24",
    processStep: "واحد فیلتراسیون (فیلتر شنی سریع با سیستم بکواش هوا و آب )",
  },
  { id: "22", idProj: "24", processStep: "واحد کلرزنی گازی" },
  { id: "23", idProj: "24", processStep: "واحد تغلیظ لجن (ثقلی )" },
  { id: "24", idProj: "24", processStep: "واحد آبگیری لجن (فیلترپرس)" },
  { id: "25", idProj: "24", processStep: "واحد بازیافت آب بک واش" },
  { id: "26", idProj: "24", processStep: "تلمبه خانه لجن غلیظ شده" },
  { id: "27", idProj: "24", processStep: "مخزن 10000 مترمکعبی" },
  { id: "28", idProj: "2", processStep: "واحد آشغالگیر دهانه درشت" },
  { id: "29", idProj: "2", processStep: "تلمبه خانه ورودی" },
  { id: "30", idProj: "2", processStep: "واحد آشغالگیر دهانه متوسط" },
  { id: "31", idProj: "2", processStep: "واحد دانه گیری" },
  { id: "32", idProj: "2", processStep: "واحد ته نشینی اولیه" },
  { id: "33", idProj: "2", processStep: "واحد راکتور بیولوژیکی (Step feed)" },
  { id: "34", idProj: "2", processStep: "واحد ته نشینی ثانویه" },
  { id: "35", idProj: "2", processStep: "واحد کلرزنی گازی" },
  { id: "36", idProj: "2", processStep: "واحد تغلیظ کننده ثقلی لجن خام" },
  { id: "37", idProj: "2", processStep: "واحد تغلیظ کننده نواری لجن اضافی" },
  {
    id: "38",
    idProj: "2",
    processStep: "واحد هاضم بی هوازی لجن ، سیستم بیوگاز و تأسیسات سولفورزدایی",
  },
  { id: "39", idProj: "2", processStep: "تجهیزات CHP" },
  { id: "40", idProj: "2", processStep: "واحد آبگیری لجن (فیلترپرس)" },
  {
    id: "41",
    idProj: "2",
    processStep:
      "تلمبه خانه های لجن اولیه ، اضافی ، برگشتی، غلیظ شده و هضم شده",
  },
  {
    id: "42",
    idProj: "2",
    processStep: "تلمبه خانه کفاب اولیه و ثانویه و برگشت زهاب",
  },
  { id: "43", idProj: "2", processStep: "سیستم حذف بو" },
  { id: "44", idProj: "2", processStep: "بسترهای خشککن لجن" },
  {
    id: "45",
    idProj: "1",
    processStep: "واحد آشغالگیر دهانه درشت و دهانه متوسط",
  },
  { id: "46", idProj: "1", processStep: "واحد دانه گیری" },
  { id: "47", idProj: "1", processStep: "واحد ته نشینی اولیه" },
  {
    id: "48",
    idProj: "1",
    processStep: "واحد راکتور بیهوازی ، راکتور انوکسیک ، راکتور هوادهی",
  },
  { id: "49", idProj: "1", processStep: "واحد ته نشینی ثانویه" },
  { id: "50", idProj: "1", processStep: "واحد کلرزنی گازی" },
  { id: "51", idProj: "1", processStep: "واحد تغلیظ کننده ثقلی لجن خام" },
  { id: "52", idProj: "1", processStep: "واحد تغلیظ کننده نواری لجن اضافی" },
  {
    id: "53",
    idProj: "1",
    processStep: "واحد آبگیری لجن (دکانتر سانتریفیوژ )",
  },
  {
    id: "54",
    idProj: "1",
    processStep: "واحد هاضم بی هوازی لجن، سیستم بیوگاز، تأسیسات سولفورزدایی",
  },
  { id: "55", idProj: "1", processStep: "تجهیزات CHP" },
  {
    id: "56",
    idProj: "1",
    processStep:
      "تلمبه خانه های لجن اولیه ، اضافی ، برگشتی، غلیظ شده و هضم شده",
  },
  {
    id: "57",
    idProj: "1",
    processStep: "تلمبه خانه های کفاب اولیه و ثانویه و برگشت زهاب",
  },
  { id: "58", idProj: "1", processStep: "سیستم حذف بو" },
  { id: "59", idProj: "4", processStep: "واحد آشغالگیر دهانه درشت" },
  { id: "60", idProj: "4", processStep: "تلمبه خانه ورودی" },
  { id: "61", idProj: "4", processStep: "واحد آشغالگیر دهانه متوسط" },
  { id: "62", idProj: "4", processStep: "واحد دانه گیری" },
  { id: "63", idProj: "4", processStep: "واحد ته نشینی اولیه" },
  { id: "64", idProj: "4", processStep: "واحد راکتور  بیهوازی، راکتور هوادهی" },
  { id: "65", idProj: "4", processStep: "واحد ته نشینی ثانویه" },
  { id: "66", idProj: "4", processStep: "واحد کلرزنی گاز" },
  { id: "67", idProj: "4", processStep: "واحد تغلیظ کننده نواری لجن اضافی" },
  { id: "68", idProj: "4", processStep: "واحد هاضم هوازی لجن" },
  {
    id: "69",
    idProj: "4",
    processStep: "واحد آبگیری مکانیکی لجن (فیلتر پرس )",
  },
  {
    id: "70",
    idProj: "4",
    processStep:
      "تلمبه خانه های لجن اولیه ، اضافی ، برگشتی، غلیظ شده و هضم شده",
  },
  {
    id: "71",
    idProj: "4",
    processStep: "تلمبه خانه کفاب اولیه، ثانویه و برگشت زهاب",
  },
  { id: "72", idProj: "4", processStep: "بسترهای خشک کن لجن" },
  { id: "281", idProj: "4", processStep: "مخزن 5000 مترمکعبی ذخیره پساب" },
  { id: "73", idProj: "3", processStep: "شیرخانه ورودی" },
  { id: "74", idProj: "3", processStep: "واحد هوادهی" },
  { id: "75", idProj: "3", processStep: "واحد میکرواسترینر" },
  { id: "76", idProj: "3", processStep: "واحد انعقاد (اختلاط سریع )" },
  {
    id: "77",
    idProj: "3",
    processStep: "واحد آماده سازی و تزریق مواد شیمیایی",
  },
  {
    id: "78",
    idProj: "3",
    processStep: "واحد لخته سازی و ته نشینی (کلاریفلوکولاتور)",
  },
  {
    id: "79",
    idProj: "3",
    processStep:
      "واحد فیلتراسیون (فیلتر دو لایه شن و آنتراسیت با سیستم بکواش هوا و آب )",
  },
  { id: "80", idProj: "3", processStep: "واحد کلرزنی گازی" },
  { id: "81", idProj: "3", processStep: "واحد تغلیظ لجن (ثقلی)" },
  { id: "82", idProj: "3", processStep: "واحد آبگیری لجن (دکانتر سانتریفیوژ)" },
  { id: "83", idProj: "3", processStep: "واحد بازیافت آب بک واش" },
  {
    id: "84",
    idProj: "3",
    processStep: "تلمبه خانه لجن غلیظ شده برگشت زهاب و آب سرویس",
  },
  { id: "85", idProj: "3", processStep: "مخزن 5000 مترمکعبی آب پاک" },
  { id: "86", idProj: "7", processStep: "شیرخانه ورودی آب خام" },
  { id: "87", idProj: "7", processStep: "واحد آشغالگیر دهانه متوسط" },
  { id: "88", idProj: "7", processStep: "واحد پیش ته نشینی" },
  { id: "89", idProj: "7", processStep: "واحد میکرواسترینر" },
  { id: "90", idProj: "7", processStep: "واحد هوادهی دیفیوزری" },
  { id: "91", idProj: "7", processStep: "واحد انعقاد (اختلاط سریع )" },
  { id: "92", idProj: "7", processStep: "واحد لخته سازی (اختلاط کند)" },
  {
    id: "93",
    idProj: "7",
    processStep: "واحد آماده سازی و تزریق مواد شیمیایی",
  },
  {
    id: "94",
    idProj: "7",
    processStep: "واحد ته نشینی مستطیلی با صفحات لاملا",
  },
  {
    id: "95",
    idProj: "7",
    processStep:
      "واحد فیلتراسیون (فیلتر دو لایه شن و آنتراسیت با سیستم بک واش هوا و آب )",
  },
  { id: "96", idProj: "7", processStep: "واحد کلرزنی گازی" },
  { id: "97", idProj: "7", processStep: "واحد بازیافت آب بک واش" },
  { id: "98", idProj: "7", processStep: "واحد ذخیره و تغلیظ ثقلی لجن" },
  { id: "99", idProj: "7", processStep: "واحد آبگیری مکانیکی (فیلترپرس)" },
  { id: "100", idProj: "7", processStep: "تلمبه خانه لجن غلیظ شده" },
  { id: "101", idProj: "8", processStep: "واحد آشغالگیر دهانه متوسط" },
  { id: "102", idProj: "8", processStep: "تلمبه خانه ورودی" },
  { id: "103", idProj: "8", processStep: "واحد دانه گیری" },
  {
    id: "104",
    idProj: "8",
    processStep: "راکتور بیهوازی – راکتور آنوکسیک – راکتور هوادهی ",
  },
  { id: "105", idProj: "8", processStep: "واحد ته نشینی" },
  { id: "106", idProj: "8", processStep: "واحد کلرزنی گازی" },
  { id: "107", idProj: "8", processStep: "واحد تغلیظ کننده ثقلی لجن" },
  { id: "108", idProj: "8", processStep: "واحد آبگیری لجن (فیلترپرس )" },
  {
    id: "109",
    idProj: "8",
    processStep: "تلمبه خانه های لجن اضافی، برگشتی و لجن غلیظ شده",
  },
  { id: "110", idProj: "8", processStep: "تلمبه خانه کفاب و برگشت زهاب" },
  { id: "111", idProj: "8", processStep: "بسترهای خشک کن لجن" },
  { id: "112", idProj: "10", processStep: "واحد آشغالگیر دهانه متوسط" },
  { id: "113", idProj: "10", processStep: "تلمبه خانه ورودی" },
  {
    id: "114",
    idProj: "10",
    processStep: "واحد دانه گیری – راکتورهای انوکسیک و هوادهی",
  },
  { id: "115", idProj: "10", processStep: "واحد ته نشینی ثانویه" },
  { id: "116", idProj: "10", processStep: "واحد کلرزنی گازی" },
  { id: "117", idProj: "10", processStep: "تلمبه خانه های لجن اضافی و برگشتی" },
  { id: "118", idProj: "10", processStep: "تلمبه خانه های کفاب و برگشت زهاب" },
  { id: "119", idProj: "10", processStep: "بسترهای خشک کن لجن " },
  {
    id: "120",
    idProj: "28",
    processStep:
      "تأمین و اجرای خط لوله فولادی و پلی اتیلن از قطر 400 تا 700 با فشار کار 25 بار",
  },
  { id: "121", idProj: "28", processStep: "اجرای حوضچه شیرآلات و راه دسترسی" },
  { id: "122", idProj: "29", processStep: "واحد آشغالگیری" },
  { id: "123", idProj: "29", processStep: "تلمبه خانه ورودی" },
  { id: "124", idProj: "29", processStep: "واحد متعادلسازی" },
  { id: "125", idProj: "29", processStep: "واحد انعقاد (اختلاط سریع )" },
  { id: "126", idProj: "29", processStep: "واحد لخته سازی (اختلاط آرام) " },
  {
    id: "127",
    idProj: "29",
    processStep: "واحد آماده سازی و تزریق مواد شیمیایی",
  },
  { id: "128", idProj: "29", processStep: "واحد ته نشینی شیمیایی" },
  {
    id: "129",
    idProj: "29",
    processStep: "واحد هوادهی (هواده دور تند نصب ثابت )",
  },
  { id: "130", idProj: "29", processStep: "واحد ته نشینی" },
  { id: "131", idProj: "29", processStep: "واحد کلرزنی (کلرمایع )" },
  {
    id: "132",
    idProj: "29",
    processStep: "واحد فیلتراسیون (فیلتر شنی تحت فشار ، فیلترهای کربن فعال)",
  },
  {
    id: "133",
    idProj: "29",
    processStep: "تلمبه خانه های لجن اضافی و برگشتی و لجن شیمیایی",
  },
  { id: "134", idProj: "29", processStep: "هاضم هوازی لجن" },
  { id: "135", idProj: "30", processStep: "واحد آشغالگیری" },
  { id: "136", idProj: "30", processStep: "تلمبه خانه ورودی" },
  { id: "137", idProj: "30", processStep: "واحد چربی گیری API" },
  { id: "138", idProj: "30", processStep: "واحد متعادل سازی" },
  { id: "139", idProj: "30", processStep: "واحد ته نشینی شیمیایی" },
  { id: "140", idProj: "30", processStep: "انتخابگر بیولوژیکی" },
  {
    id: "141",
    idProj: "30",
    processStep: "واحد هوادهی (هواده دور کند نصب ثابت)",
  },
  { id: "142", idProj: "30", processStep: "واحد ته نشینی" },
  { id: "143", idProj: "30", processStep: "واحد کلرزنی (کلر مایع)" },
  { id: "144", idProj: "30", processStep: "واحد تغلیظ ثقلی لجن" },
  { id: "145", idProj: "30", processStep: "واحد هاضم هوازی" },
  { id: "146", idProj: "30", processStep: "بسترهای خشک کن لجن" },
  {
    id: "147",
    idProj: "30",
    processStep: "تلمبه خانه های لجن خام، اضافی و برگشتی",
  },
  { id: "148", idProj: "31", processStep: "واحد تلمبه خانه ورودی" },
  { id: "149", idProj: "31", processStep: "واحد آشغالگیر دهانه متوسط" },
  {
    id: "150",
    idProj: "31",
    processStep: "لاگون هوادهی (هواده سطحی دور تند نصب شناور)",
  },
  { id: "151", idProj: "31", processStep: "لاگون ته نشینی" },
  { id: "152", idProj: "31", processStep: "واحد کلرزنی (کلرمایع )" },
  { id: "153", idProj: "6", processStep: "ایستگاه پمپاژ ورودی" },
  { id: "154", idProj: "6", processStep: "واحد آشغالگیر دهانه ریز" },
  { id: "155", idProj: "6", processStep: "واحد دانه گیری" },
  { id: "156", idProj: "6", processStep: "واحد ته نشینی اولیه" },
  { id: "157", idProj: "6", processStep: "راکتور آنوکسیک - راکتور هوادهی" },
  { id: "158", idProj: "6", processStep: "واحد ته نشینی ثانویه" },
  { id: "159", idProj: "6", processStep: "واحد میکرواسترینر" },
  { id: "160", idProj: "6", processStep: "گند زدایی با UV" },
  { id: "161", idProj: "6", processStep: "واحد تغلیظ کننده نواری لجن" },
  { id: "162", idProj: "6", processStep: "واحد هاضم هوازی لجن" },
  { id: "163", idProj: "6", processStep: "واحد آبگیری لجن (سانتریفیوژ)" },
  {
    id: "164",
    idProj: "6",
    processStep:
      "تلمبه خانه های لجن اولیه، اضافی ، برگشتی و لجن غلیظ شده و هضم شده",
  },
  { id: "165", idProj: "6", processStep: "تلمبه خانه آب سرویس" },
  { id: "166", idProj: "6", processStep: "لاگون های خشک کن لجن" },
  { id: "167", idProj: "32", processStep: "واحد آشغالگیر دهانه متوسط" },
  { id: "168", idProj: "32", processStep: "واحد متعادلسازی" },
  {
    id: "169",
    idProj: "32",
    processStep: "واحد هوادهی (هواده دور تند نصب شناور )",
  },
  { id: "170", idProj: "32", processStep: "واحد ته نشینی ثقلی" },
  { id: "171", idProj: "32", processStep: "واحد کلرزنی (کلر مایع )" },
  { id: "172", idProj: "32", processStep: "واحد تغلیظ ثقلی لجن" },
  { id: "173", idProj: "32", processStep: "بسترهای خشک کن لجن" },
  {
    id: "174",
    idProj: "21",
    processStep: "واحد فیلتراسیون مستقیم (فیلتر شنی تحت فشار )",
  },
  { id: "175", idProj: "21", processStep: "واحد کلرزنی گازی" },
  { id: "176", idProj: "20", processStep: "تلمبه خانه ورودی" },
  { id: "177", idProj: "20", processStep: "واحد آشغالگیری دهانه متوسط" },
  {
    id: "178",
    idProj: "20",
    processStep: "لاگون هوادهی (هواده سطحی دور کند نصب ثابت )",
  },
  { id: "179", idProj: "20", processStep: "لاگون ته نشینی" },
  { id: "180", idProj: "20", processStep: "واحد کلرزنی گازی" },
  { id: "181", idProj: "11", processStep: "شیرخانه ورودی" },
  { id: "182", idProj: "11", processStep: "واحد ته نشینی مقدماتی" },
  { id: "183", idProj: "11", processStep: "واحد انعقاد (اختلاط سریع)" },
  {
    id: "184",
    idProj: "11",
    processStep: "واحد آماده سازی و تزریق مواد شیمیایی",
  },
  { id: "185", idProj: "11", processStep: "واحد ته نشینی (پولساتور)" },
  {
    id: "186",
    idProj: "11",
    processStep: "واحد فیلتراسیون (فیلتر شنی ثقلی با سیستم بک واش آب و هوا)",
  },
  { id: "187", idProj: "11", processStep: "واحد کلرزنی گازی" },
  { id: "188", idProj: "11", processStep: "واحد بازیافت آب بک واش" },
  { id: "197", idProj: "12", processStep: "واحد آشغالگیری" },
  {
    id: "198",
    idProj: "12",
    processStep: "لاگون هوادهی ( هواده دور تند و دور کند نصب ثابت )",
  },
  { id: "199", idProj: "12", processStep: "لاگون های ته نشینی" },
  { id: "200", idProj: "12", processStep: "واحد کلرزنی گازی" },
  { id: "201", idProj: "22", processStep: "واحد آشغالگیری" },
  { id: "202", idProj: "22", processStep: "واحد دانه گیری" },
  {
    id: "203",
    idProj: "22",
    processStep: "لاگون هوادهی (هوادهی سطحی دور تند نصب شناور)",
  },
  { id: "204", idProj: "22", processStep: "لاگون ته نشینی" },
  { id: "205", idProj: "22", processStep: "واحد کلرزنی گازی" },
  { id: "206", idProj: "13", processStep: "واحد دانه گیری" },
  {
    id: "207",
    idProj: "13",
    processStep: "لاگون هوادهی (هوادهی سطحی دور تند نصب ثابت)",
  },
  { id: "208", idProj: "13", processStep: "لاگون ته نشینی" },
  { id: "209", idProj: "13", processStep: "واحد کلرزنی گازی" },
  { id: "210", idProj: "23", processStep: "واحد آشغالگیری" },
  {
    id: "211",
    idProj: "23",
    processStep: "لاگون هوادهی (هواده های دور تند نصب شناور)",
  },
  { id: "212", idProj: "23", processStep: "لاگون ته نشینی" },
  { id: "213", idProj: "23", processStep: "واحد کلرزنی گازی" },
  { id: "214", idProj: "25", processStep: "واحد آشغالگیری" },
  {
    id: "215",
    idProj: "25",
    processStep: "واحد تلمبه خانه (تلمبه های مستغرق)",
  },
  { id: "216", idProj: "25", processStep: "واحد حفاظت در مقابل ضربه قوچ" },
  { id: "217", idProj: "15", processStep: "تلمبه خانه ورودی" },
  { id: "218", idProj: "15", processStep: "واحد آشغالگیری" },
  { id: "219", idProj: "15", processStep: "واحد دانه گیری" },
  {
    id: "220",
    idProj: "15",
    processStep: "واحد هوادهی (هواده سطحی دور تند نصب ثابت)",
  },
  { id: "221", idProj: "15", processStep: "واحد ته نشینی" },
  { id: "222", idProj: "15", processStep: "واحد کلرزنی گازی" },
  { id: "223", idProj: "15", processStep: "واحد تغلیظ ثقلی لجن" },
  { id: "224", idProj: "15", processStep: "بسترهای خشک کن لجن" },
  {
    id: "225",
    idProj: "15",
    processStep: "تلمبه خانه های لجن برگشتی و اضافی و برگشت زهاب",
  },
  { id: "226", idProj: "9", processStep: "واحد آشغالگیری" },
  { id: "227", idProj: "9", processStep: "واحد چربی گیری API" },
  { id: "228", idProj: "9", processStep: "واحد متعادلسازی" },
  { id: "229", idProj: "9", processStep: "واحد انعقاد (اختلاط سریع)" },
  { id: "230", idProj: "9", processStep: "واحد لخته سازی (اختلاط آرام)" },
  { id: "231", idProj: "9", processStep: "واحدچربی گیری DAF" },
  { id: "232", idProj: "9", processStep: "واحد هوادهی (هوادهی دیفیوزری)" },
  { id: "233", idProj: "9", processStep: "واحد ته نشینی" },
  {
    id: "234",
    idProj: "9",
    processStep: "واحد فیلتراسیون (فیلترهای تحت فشار شنی و کربنی)",
  },
  { id: "235", idProj: "9", processStep: "واحد کلرزنی (کلر مایع)" },
  {
    id: "236",
    idProj: "9",
    processStep:
      "تلمبه خانه های لجن برگشتی و اضافی، لجن غلیظ شده و لجن هضم شده",
  },
  { id: "237", idProj: "9", processStep: "تلمبه خانه لجن و روغن شیمیایی" },
  { id: "238", idProj: "9", processStep: "تغلیظ کننده ثقلی لجن اضافی" },
  { id: "239", idProj: "9", processStep: "هاضم هوازی لجن (هوادهی دیفیوزری )" },
  { id: "240", idProj: "9", processStep: "تلمبه خانه آب سرویس" },
  {
    id: "241",
    idProj: "9",
    processStep: "آبگیری لجن بیولوژیک (بلت فیلترپرس)",
  },
  {
    id: "242",
    idProj: "9",
    processStep: "واحدآماده سازی و تزریق مواد شیمیایی",
  },
  {
    id: "243",
    idProj: "9",
    processStep: "آبگیری لجن شیمیایی (دکانتر سانتریفیوژ)",
  },
  { id: "244", idProj: "14", processStep: "واحد آشغالگیری دهانه متوسط" },
  {
    id: "245",
    idProj: "14",
    processStep: "واحد لاگون هوادهی ( هوادهی عمقی شناور )",
  },
  { id: "246", idProj: "14", processStep: "واحد ته نشینی ثانویه" },
  { id: "247", idProj: "14", processStep: "واحد کلرزنی گازی" },
  { id: "248", idProj: "14", processStep: "واحد هاضم هوازی (هوادهی عمقی)" },
  {
    id: "249",
    idProj: "14",
    processStep: "تلمبه خانه های لجن برگشتی و اضافی و برگشت زهاب",
  },
  { id: "250", idProj: "17", processStep: "واحد آشغالگیری" },
  {
    id: "251",
    idProj: "17",
    processStep: "واحد لاگون هوادهی ( هوادهی دور کند نصب ثابت )",
  },
  { id: "252", idProj: "17", processStep: "واحد لاگون ته نشینی" },
  { id: "253", idProj: "17", processStep: "واحد کلرزنی مایع" },
  { id: "254", idProj: "16", processStep: "واحد آشغالگیری" },
  { id: "255", idProj: "16", processStep: "واحد دانه گیری" },
  {
    id: "256",
    idProj: "16",
    processStep: "واحد هوادهی ( هواده دور کند نصب ثابت)",
  },
  { id: "257", idProj: "16", processStep: "واحد ته نشینی" },
  { id: "258", idProj: "16", processStep: "واحد کلرزنی مایع" },
  { id: "259", idProj: "16", processStep: "واحد آبگیری لجن (بلت فیلترپرس)" },
  {
    id: "260",
    idProj: "16",
    processStep: "تلمبه خانه های لجن برگشتی، اضافی و لجن غلیظ شده",
  },
  { id: "261", idProj: "18", processStep: "واحد آشغالگیری دهانه متوسط" },
  { id: "262", idProj: "18", processStep: "تلمبه خانه ورودی" },
  { id: "263", idProj: "18", processStep: "واحد دانه گیری" },
  { id: "264", idProj: "18", processStep: "واحد انتخابگر بیولوژیک" },
  {
    id: "265",
    idProj: "18",
    processStep: "واحد هوادهی (هواده دورکند نصب ثابت)",
  },
  { id: "266", idProj: "18", processStep: "واحد ته نشینی" },
  { id: "267", idProj: "18", processStep: "واحد کلرزنی گازی" },
  { id: "268", idProj: "18", processStep: "واحد تغلیظ ثقلی لجن" },
  { id: "269", idProj: "18", processStep: "واحد آبگیری لجن (بلت فیلترپرس)" },
  {
    id: "270",
    idProj: "18",
    processStep: "تلمبه خانه های لجن برگشتی، اضافی، لجن غلیظ شده",
  },
  { id: "271", idProj: "18", processStep: "تلمبه خانه برگشت زهاب" },
  { id: "272", idProj: "18", processStep: "تلمبه خانه آبیاری محوطه" },
  { id: "273", idProj: "19", processStep: "واحد آشغالگیری" },
  { id: "274", idProj: "19", processStep: "واحد دانه گیری" },
  {
    id: "275",
    idProj: "19",
    processStep: "واحد لاگون هوادهی (هوادهی دور تند نصب شناور)",
  },
  { id: "276", idProj: "19", processStep: "واحد لاگون ته نشینی" },
  { id: "277", idProj: "19", processStep: "واحد کلرزنی گازی" },
  { id: "278", idProj: "27", processStep: "آبگیر شناور (پانتون) " },
  {
    id: "279",
    idProj: "27",
    processStep: "تلمبه خانه مستقر در پانتون به ظرفیت 500 لیتر در ثانیه ",
  },
  {
    id: "280",
    idProj: "27",
    processStep:
      "خط انتقال شناور ( دو خط موازی از لوله پلی اتیلن هر یک به قطر 500 میلی متر مجهز به rubber hose)",
  },
];
export { ProcessStepData };
